steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/IMAGE:${TAG_NAME/v//}
  - --cache=true
  - --cache-ttl=48h
  - --context=./
  id: build
timeout: 3600s
