steps:
- name: ubuntu
  id: test
  args:
    - echo
    - ${REPO_NAME#\/}
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/${REPO_NAME#\/}:$SHORT_SHA
  - --cache=true
  - --cache-ttl=48h
  - --context=./
  id: build
timeout: 3600s
options:
  dynamic_substitutions: true
