substitutions:
  # See if this is either a tag or a PR
  _TAG_NAME: ${TAG_NAME:-${_HEAD_BRANCH}}
  # Replace "/" with "-" in branch name
  _TAG_REPLACE: ${_TAG_NAME/\//-}
    # If it's a PR, image tag will be the Head Branch
    # If it's a tag, image tag will be the tag
    # If it's not a tag or a PR, then it should be latest
  _IMAGE_NAME: ${REPO_NAME#*/}:${_TAG_REPLACE:-latest}
steps:
  # use Kaniko and --single-snapshot to reduce image size
  # No need to combine multiple statements in a Dockerfile to reduce image size
- name: 'gcr.io/kaniko-project/executor:latest'
  id: build
  args:
  - --destination=gcr.io/$PROJECT_ID/${_IMAGE_NAME}
  - --cache=true
  - --cache-ttl=48h
  - --single-snapshot
  - --context=./
timeout: 3600s
options:
  dynamic_substitutions: true
